language: python
python:
	- "3.4"
	- "3.5"
	- "3.6"
addons:
	apt:
		packages:
			- libxml2-dev
			- libxslt1-dev
				- zlib1g-dev
				- libffi-dev
				- libyaml-dev
				- libssl-dev

install:
	- pip install -U pipenv
	- pipenv install --dev

script: pipenv run nosetests
sudo: false
deploy:
	provider: pypi
	user: "dragonmaster"
	password:
		secure: "Z5ISKqPgzztXtzJDuDLnHocpMrOO547dxgObHeZk83iViajw3j6da5sOG74CchTQsNI0CNlAr6OtxVwTNkRaiSM1glY1PaLxxl259mCA59fMfTnX7jz36MdHpBhZpLi09If4JlJOGpV2n0SqPZvwlCPSJIRrSqqhGJ8MPdf6VRi0ij0Y9rnDpBVdQ9Yi9e8oTP2f/xZKsbFX3TaCDgSCZMPJxGQt0TzJIfqRr1dHZUm6+N6xlv51BinEZIMCnl24gQEBLk1MOgBeqoX893IyEPRFHAp+T+kFfdldEAzmx6kAE7S4S15Kj/Wx/KRrbd50MztxOv1spAJ7hcgPWXjs/8iLtE9ed+AaDubeO7Hn4mUo2iWSX8f3Fhmzd15ZNd2lKVugfKdWl2FdCSrXYJIiVn2CRJRMDOTU3VF72dvlM+b53jhP+5Cd6BGIMRCNi+TjCAZEJyn4uuCOWE9CKeDf0lG61tKWsR6hUvbCDwSTyys+3dC2KMmOJy1aak4rVqtvyMcc+ICxcAEYJzfQMRYKT0PiWvkWNIosszyfFXydArpYtoQbLo22/E2h3Uee47D9VOozSejf99qDNuc1t6KJNfuLU/iaj91xweo70S94SmjdmMe+kRXErckPJY7u6JNuMsiltpyKlcRWEhq9kKh88dHMNIwSgsRc7hVRtXmRYls="
	distributions: "bdist_wheel"
	on:
		tags: true
